*&---------------------------------------------------------------------*
*&  Include           CVI_COCKPIT_D
*&---------------------------------------------------------------------*
DATA: BEGIN OF tab,
        vald TYPE string,
        prep TYPE string,
        load TYPE string,
        upgd TYPE string,
      END OF tab,
      "status icon
      BEGIN OF stat,
        vald_nc    TYPE string,
        vald_lib   TYPE string,
        prep_mdc   TYPE string,
        prep_ac    TYPE string,
        prep_sup   TYPE string,
        upgd_ppo   TYPE string,
        upgd_preck TYPE string,
        load_prein TYPE string,
        load_blktr TYPE string,
        load_fi    TYPE string,
        load_ltool TYPE string,
        load_cchk  TYPE string,
        load_ppo   TYPE string,
        load_posin TYPE string,
        load_reltr TYPE string,
      END OF stat,

      BEGIN OF change_on,
        vald_nc    TYPE char10,
        vald_lib   TYPE char10,
        prep_mdc   TYPE char10,
        prep_ac    TYPE char10,
        prep_sup   TYPE char10,
        upgd_ppo   TYPE char10,
        upgd_preck TYPE char10,
        load_prein TYPE char10,
        load_blktr TYPE char10,
        load_fi    TYPE char10,
        load_ltool TYPE char10,
        load_cchk  TYPE char10,
        load_ppo   TYPE char10,
        load_posin TYPE char10,
        load_reltr TYPE char10,
      END OF change_on,

      BEGIN OF change_by,
        vald_nc    TYPE uname,
        vald_lib   TYPE uname,
        prep_mdc   TYPE uname,
        prep_ac    TYPE uname,
        prep_sup   TYPE uname,
        upgd_ppo   TYPE uname,
        upgd_preck TYPE uname,
        load_prein TYPE uname,
        load_blktr TYPE uname,
        load_fi    TYPE uname,
        load_ltool TYPE uname,
        load_cchk  TYPE uname,
        load_ppo   TYPE uname,
        load_posin TYPE uname,
        load_reltr TYPE uname,
      END OF change_by.
